BBBB BBBB

BBBBB BBBBBBB

  BB BBBBB
    XX XXXXXXXXXXXXXXXXXXXX XXXXXX XXX X XXXXX XXXXXXXX XX XXXXXXXXXXXX
  BBBBB
  XX X gettext(u'Database Query System') XXXX
  XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX

    XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXX
  
   XXXXXX XXXXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX

    XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XX
    XXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXFFFFFFX XX
  XXXXXXX

BBBBBBBB
