XXXXXXXXXXXXXXXXXXXXXXXX
XXXXXX
    XXXXXXXXXXXXXXXXXXXXX
XXXXXXX
XXXXXX
    BB BBBBB
        XX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXX X XXXXXX XXXXXXXXX
    BBBBB
    BB BBBBBB
        XX XXXXXXXXXXXXX XXXXXXXXXX XXXXX XX XX XXXXXXXX
    BBBBB

   XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
        BBBBBBBBBB
         XXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XX XXXXXXXXXX
        XXXXXX XXXXXXXXXXXX  XXXXXXXXXXXXXX
    XXXXXXX
XXXXXXX
XXXXXXX
